version: "3.1"
services:
  db:
    image: mysql:8.0.28
    environment:
      MYSQL_ROOT_PASSWORD: "passw@rd"
    ports:
      - "3306:3306"
    volumes:
      - ./tmp/mysql/data:/var/lib/mysql

  app:
    build: ./docker/app
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "8080:80"
    depends_on:
      - db